# The URL the site will be built for
base_url = "https://iswindowsonarmready.netlify.app"

title = "Is Windows on ARM ready?"
description = "Tracking ARM versions of popular Windows applications"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true